### ISSUE TITLE
Conflicting id types throws validation error

### ISSUE THREAD

**Issue by fredrowland** [BeggarsOpera/TEI-MEI#1]
conflicting ID-types for attribute "id" from namespace "http://www.w3.org/XML/1998/namespace" of element "notesStmt" from         namespace "http://www.music-encoding.org/ns/mei"

Issue resolved using this method: https://github.com/faustedition/faust-schema/issues/2 -> As a workaround, go to Options → Preferences in Oxygen, and on the XML / XML Parser / RELAX NG page, uncheck Check ID/IDREF.

**Comment by fakefrowland** [comment]
obsolete issue
